FROM tensorflow/tensorflow
RUN pip install flask  -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
RUN pip install requests  -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
RUN pip install gevent==1.4.0  -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
RUN pip install pillow==6.1.0  -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
#RUN pip install tensorflow==1.14.0 
RUN pip install keras==2.2.4  -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
RUN pip install uwsgi==2.0.18  -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
COPY model /root/.keras/models/
#COPY tensorflow-1.14.0-cp35-none-linux_armv7l.whl /home
#RUN pip install tensorflow-1.14.0-cp35-none-linux_armv7l.whl

COPY *.py /app/
CMD ["python","/app/app.py"]~
#CMD ["uwsgi", "--http", ":5211", "--wsgi-file", "app.py", "--callable", "app", "--master", "--processes", "1", "--threads", "1"]
